### ISSUE TITLE
Add default values for some form fields

### ISSUE THREAD

**Issue by jsstrn** [spinningarrow/twsg-air-con-request#5]
To make it more convenient for users when filling out the form, we can consider using default values for start and end times, since most events run on weekdays and start from 6pm and end at 10pm.

Also, for requester's contact number we could put the ThoughtWorks office phone number? This is just for convenience and if users want to they can always replace it with their own mobile numbers.

**Comment by spinningarrow** [comment]
Good idea! Kiran suggested 7pm - 9pm (I think the regular AC stops around 6-6.30 and it should stay cool for an thirty minutes to an hour.)
